services:
  app:
    build: .
    container_name: car_rent_app
    working_dir: /var/www/html
    restart: "no"
    tty: true
    stdin_open: true
    
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8001"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=car_rent
      - DB_USERNAME=caruser
      - DB_PASSWORD=carpass
    depends_on:
      - db
    # Ta linia uruchomi serwer i utrzyma kontener przy Å¼yciu
    command: tail -f /dev/null

  db:
    image: postgres:15
    container_name: car_rent_db
    environment:
      POSTGRES_DB: car_rent
      POSTGRES_USER: caruser
      POSTGRES_PASSWORD: carpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
